name: Try

permissions:
  id-token: write
  contents: read

on:
  - push


jobs:
  deploy:
    runs-on: macos-latest

    name: Build 🚀
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker
        run: |
          brew install docker
          brew install colima
          brew services start colima
          colima start
          docker ps

