name: Try

permissions:
  id-token: write
  contents: read

on:
  - push


jobs:
  deploy:
    runs-on: macos-latest

    name: Build 🚀
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker
        run: |
          arch -arm64 brew install docker
          arch -arm64 brew install docker docker-compose
          arch -arm64 brew install colima
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          arch -arm64 brew services start colima
          docker ps

