name: Try

permissions:
  id-token: write
  contents: read

on:
  - push


jobs:
  deploy:
    runs-on: macos-latest

    name: Build 🚀
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker
        run: |
          arch -arm64 brew --cask install docker
          arch -arm64 brew install colima
          arch -arm64 brew services start docker
          arch -arm64 brew services start colima
          docker ps

