name: Deploy Now 🚀

permissions:
  id-token: write
  contents: read
  issues: write

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment to deploy to
      DEPLOY_AUTH:
        type: string
        required: true
        default: true
        description: DEPLOY_AUTH
      DEPLOY_BACKEND:
        type: string
        required: true
        default: true
        description: DEPLOY_BACKEND
      DEPLOY_DATA_AIRFLOW:
        type: string
        required: true
        default: true
        description: DEPLOY_DATA_AIRFLOW
      DEPLOY_FEATURES_API:
        type: string
        required: true
        default: false
        description: DEPLOY_FEATURES_API
      DEPLOY_ROUTES:
        type: string
        required: true
        default: false
        description: DEPLOY_ROUTES
      DEPLOY_SM2A:
        type: string
        required: true
        default: true
        description: DEPLOY_SM2A
      DEPLOY_MONITORING:
        type: string
        required: true
        default: false
        description: DEPLOY_MONITORING

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

run-name: Deploy to ${{ inputs.environment }} environment by @${{ github.actor }}

jobs:
  deploy-veda-auth:
    name: Deploy VEDA auth 🔐
    runs-on: ubuntu-latest
    
    env:
      DIRECTORY: veda-auth
      ENVIRONMENT: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    if: ${{ inputs.DEPLOY_AUTH == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"

      - name: Run auth deployment
        id: deploy_auth_stack
        shell: bash
        run: echo "Deploying VEDA AUTH"


  deploy-veda-backend:
    name: Deploy VEDA backend ⚙️
    runs-on: ubuntu-latest
    env:
      DIRECTORY: veda-backend
      ENVIRONMENT: ${{ inputs.environment }}
    needs: [deploy-veda-auth]
    if: ${{ inputs.DEPLOY_BACKEND == 'true' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"

      - name: Run backend deployment
        id: deploy_backend_stack
        shell: bash
        run: echo "Deploying VEDA BACKEND"


  deploy-veda-data-airflow:
    name: deploy VEDA data airflow 🍃
    runs-on: ubuntu-latest
    env:
      DIRECTORY: veda-data-airflow
      AWS_REGION: "us-west-2"
      ENVIRONMENT: ${{ inputs.environment }}
    needs: [deploy-veda-auth, deploy-veda-backend]
    if: ${{ inputs.DEPLOY_DATA_AIRFLOW == 'true' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"


      - name: Run deploy-veda-data-airflow deployment
        id: deploy-veda-data-airflow
        shell: bash
        run: echo "Deploying VEDA deploy-veda-data-airflow"


  deploy-veda-data-airflow-sm2a:
    name: deploy VEDA data airflow SM2A 🛸
    runs-on: ubuntu-latest
    env:
      DIRECTORY: veda-data-airflow
      AWS_REGION: "us-west-2"
      ENVIRONMENT: ${{ inputs.environment }}
    if: ${{ inputs.DEPLOY_SM2A == 'true' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"


      - name: Run deploy-veda-data-airflow-sm2a deployment
        id: deploy-veda-data-airflow-sm2a
        shell: bash
        run: echo "Deploying VEDA deploy-veda-data-airflow-sm2aw"

    outputs:
      workflows_sm2a_api_value: dfff

  deploy-veda-features-api:
    name: Deploy VEDA features-api 🗺️
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ inputs.DEPLOY_FEATURES_API == 'true' }}
    env:
      DIRECTORY: veda-features-api-cdk
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"

      - name: Run deploy-veda-features-api deployment
        id: deploy-veda-features-api
        shell: bash
        run: echo "Deploying VEDA deploy-veda-features-api"

    outputs:
      features_api_stack_name: cecec

  deploy-veda-monitoring:
    name: deploy VEDA monitoring 👁️
    runs-on: ubuntu-latest
    env:
      DIRECTORY: veda-monitoring
      AWS_REGION: "us-west-2"
      ENVIRONMENT: ${{ inputs.environment }}
      GH_PAT_CHECK: ${{ secrets.GH_PAT }}
    if: ${{ inputs.DEPLOY_MONITORING == 'true' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        if: ${{ env.GH_PAT_CHECK != '' }}
        uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "false"

      - name: Run deploy-veda-monitoring deployment
        id: deploy-veda-monitoring
        shell: bash
        run: |
          echo "Deploying VEDA deploy-veda-monitoring"
          echo ${{ inputs.DEPLOY_MONITORING }}

  